name: Gilmar Oliveira
description: Meu blog pessoal
meta_description: "Gilmar Oliveira, meu blog pessoal"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 
domain_name: "https://gilmarodp.github.io/"
google_analytics: "G-TP354KJGMV"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Gilmar Oliveira"

# Disqus config
disqus-shortname: ""
